package io.github.feddericovonwernich.spring_ai.telegram_bot.services;

import io.github.feddericovonwernich.spring_ai.function_calling_service.spi.AssistantResponse;
import io.github.feddericovonwernich.spring_ai.telegram_bot.models.AssistantThread;

/**
 * Provides services for managing AssistantThread instances associated with users.
 */
public interface AssistantThreadService {

    /**
     * Retrieves the latest AssistantThread for a specific user.
     * This thread represents the most recent interaction between the user and the assistant.
     *
     * @param userId The identifier for the user whose latest thread is to be fetched.
     * @return The latest AssistantThread associated with the given userId. If no thread is found, may return null.
     */
    AssistantThread getLatestThreadForUser(String userId);

    /**
     * Saves or updates the thread ID in the context of a user and an AssistantResponse.
     * This typically involves recording the association between a specific user conversation thread
     * and the response generated by the assistant.
     *
     * @param userId           The identifier for the user whose thread ID is to be saved or updated.
     * @param assistantResponse The AssistantResponse associated with the specific user thread.
     */
    void saveThreadIdForUser(String userId, AssistantResponse assistantResponse);
}
